import os

lines = []
L = lines.append

L('import pandas as pd')
L('import matplotlib.pyplot as plt')
L('import numpy as np')
L('from pathlib import Path')
L('')
L('class Analyzer:')
L('    def __init__(self, csv_path):')
L('        self.df = pd.read_csv(csv_path)')
L('        self.output_dir = Path(csv_path).parent / "resultados"')
L('        self.output_dir.mkdir(exist_ok=True)')
L('')
L('    def info_general(self):')
L('        print("=" * 60)')
L('        print("INFORME GENERAL")')
L('        print("=" * 60)')
L('        if "participante_id" in self.df.columns:')
L('            num_participantes = self.df["participante_id"].nunique()')
L('            denom = num_participantes if num_participantes else 1')
L('        else:')
L('            if "timestamp_inicio" in self.df.columns:')
L('                num_participantes = self.df["timestamp_inicio"].nunique()')
L('                denom = num_participantes if num_participantes else 1')
L('            else:')
L('                num_participantes = len(self.df)')
L('                denom = 1')
L('        print(f"Numero de participantes: {num_participantes}")')
L('        print(f"Numero total de respuestas: {len(self.df)}")')
L('        print(f"Respuestas por participante: {len(self.df) / denom:.1f}")')
L('        print()')
L('        print("--- Distribucion demografica ---")')
L('        print("Edad:")')
L('        print(self.df["edad"].value_counts())')
L('        print("Genero:")')
L('        print(self.df["genero"].value_counts())')
L('        print("Nivel de estudios:")')
L('        print(self.df["estudios"].value_counts())')
L('')
L('    def estadisticas_molestia(self):')
L('        print()')
L('        print("=" * 60)')
L('        print("ESTADISTICAS DE MOLESTIA (0-10)")')
L('        print("=" * 60)')
L('        if "molestia_ref_before" in self.df.columns:')
L('            ref_df = self.df.drop_duplicates("participante_id")')
L('            ref_stats = ref_df["molestia_ref_before"].astype(float).describe()')
L('            print()')
L('            print("Molestia audio referencia (antes del cuestionario):")')
L('            print(ref_stats)')
L('        stats = self.df["molestia"].astype(int).describe()')
L('        print()')
L('        print("Molestia audios (18 respuestas por participante):")')
L('        print(stats)')
L('        print()')
L('        print("--- Por tipo de ruido ---")')
L('        ruido_stats = self.df.groupby("ruido")["molestia"].agg(["mean", "std", "min", "max"])')
L('        print(ruido_stats)')
L('        print()')
L('        print("--- Por mensaje ---")')
L('        mensaje_stats = self.df.groupby("mensaje")["molestia"].agg(["mean", "std", "min", "max"])')
L('        print(mensaje_stats)')
L('        print()')
L('        print("--- Por nivel ---")')
L('        nivel_stats = self.df.groupby("nivel")["molestia"].agg(["mean", "std", "min", "max"])')
L('        print(nivel_stats)')
L('        print()')
L('        print("--- Por combinacion ruido x nivel ---")')
L('        combinacion = self.df.groupby(["ruido", "nivel"])["molestia"].agg(["mean", "std"]).round(2)')
L('        print(combinacion)')
L('        return self.df.groupby(["ruido", "nivel"])["molestia"].mean().unstack()')
L('')
L('    def estadisticas_fuentes(self):')
L('        print()')
L('        print("=" * 60)')
L('        print("ESTADISTICAS DE FUENTES SONORAS")')
L('        print("=" * 60)')
L('        todas_fuentes = []')
L('        for f in self.df["fuentes"]:')
L('            if pd.notna(f):')
L('                fuentes = [x.strip() for x in str(f).split(";")]')
L('                todas_fuentes.extend(fuentes)')
L('        from collections import Counter')
L('        conteo = Counter(todas_fuentes)')
L('        print()')
L('        print("Frecuencia de deteccion de fuentes:")')
L('        for fuente, count in conteo.most_common():')
L('            pct = count / len(self.df) * 100')
L('            print(f"  {fuente}: {count} ({pct:.1f}%)")')
L('        return conteo')
L('')
L('    def estadisticas_afectivas(self):')
L('        print()')
L('        print("=" * 60)')
L('        print("ESTADISTICAS DE PERCEPCION AFECTIVA (1-5)")')
L('        print("=" * 60)')
L('        afectivas = ["afectiva_agradable", "afectiva_caotico", "afectiva_estimulante",')
L('                     "afectiva_sinactividad", "afectiva_calmado", "afectiva_molesto",')
L('                     "afectiva_conactividad", "afectiva_monotono"]')
L('        for af in afectivas:')
L('            nombre = af.replace("afectiva_", "").capitalize()')
L('            stats = self.df[af].astype(int).describe()')
L('            print(f"{nombre}:")')
L('            print(f"  Media: {stats[\"mean\"]:.2f}")')
L('            print(f"  Std: {stats[\"std\"]:.2f}")')
L('            print(f"  Min: {stats[\"min\"]:.0f}, Max: {stats[\"max\"]:.0f}")')
L('        print()')
L('        print("--- Por tipo de ruido ---")')
L('        afectivas_ruido = self.df.groupby("ruido")[afectivas].mean().round(2)')
L('        print(afectivas_ruido)')
L('        return afectivas_ruido')
L('')
L('    def generar_graficos(self):')
L('        print()')
L('        print("=" * 60)')
L('        print("GENERANDO GRAFICOS")')
L('        print("=" * 60)')
L('        fig, axes = plt.subplots(2, 2, figsize=(14, 10))')
L('        ax1 = axes[0, 0]')
L('        molestia_ruido = self.df.groupby("ruido")["molestia"].mean().sort_values(ascending=False)')
L('        bars1 = ax1.bar(molestia_ruido.index, molestia_ruido.values, color=["#e74c3c", "#3498db", "#2ecc71"])')
L('        ax1.set_title("Molestia media por tipo de ruido")')
L('        ax1.set_ylabel("Molestia (0-10)")')
L('        ax1.set_ylim(0, 10)')
L('        for bar, val in zip(bars1, molestia_ruido.values):')
L('            ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.1, f"{val:.2f}", ha="center")')
L('        ax2 = axes[0, 1]')
L('        molestia_nivel = self.df.groupby("nivel")["molestia"].mean()')
L('        orden_nivel = ["low", "equal", "high"]')
L('        molestia_nivel = molestia_nivel.reindex(orden_nivel)')
L('        bars2 = ax2.bar(molestia_nivel.index, molestia_nivel.values, color=["#27ae60", "#f39c12", "#c0392b"])')
L('        ax2.set_title("Molestia media por nivel")')
L('        ax2.set_ylabel("Molestia (0-10)")')
L('        ax2.set_ylim(0, 10)')
L('        for bar, val in zip(bars2, molestia_nivel.values):')
L('            ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.1, f"{val:.2f}", ha="center")')
L('        ax3 = axes[1, 0]')
L('        molestia_combinacion = self.df.groupby(["ruido", "nivel"])["molestia"].mean().unstack()')
L('        molestia_combinacion = molestia_combinacion.reindex(columns=["low", "equal", "high"])')
L('        molestia_combinacion.plot(kind="bar", ax=ax3, colormap="viridis")')
L('        ax3.set_title("Molestia: Ruido x Nivel")')
L('        ax3.set_ylabel("Molestia (0-10)")')
L('        ax3.set_ylim(0, 10)')
L('        ax3.legend(title="Nivel")')
L('        ax3.set_xticklabels(ax3.get_xticklabels(), rotation=0)')
L('        ax4 = axes[1, 1]')
L('        afectivas = ["afectiva_agradable", "afectiva_caotico", "afectiva_estimulante",')
L('                     "afectiva_sinactividad", "afectiva_calmado", "afectiva_molesto",')
L('                     "afectiva_conactividad", "afectiva_monotono"]')
L('        nombres = ["Agradable", "Caotico", "Estimulante", "Sin act.", "Calmado", "Molesto", "Con act.", "Monotono"]')
L('        media_afectivas = self.df[afectivas].mean()')
L('        bars4 = ax4.bar(nombres, media_afectivas.values, color=["#9b59b6", "#e67e22", "#1abc9c", "#95a5a6", "#34495e", "#e74c3c", "#3498db", "#7f8c8d"])')
L('        ax4.set_title("Percepcion afectiva media")')
L('        ax4.set_ylabel("Puntuacion (1-5)")')
L('        ax4.set_ylim(0, 5)')
L('        ax4.axhline(y=3, color="red", linestyle="--", alpha=0.5, label="Neutral")')
L('        for bar, val in zip(bars4, media_afectivas.values):')
L('            ax4.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.05, f"{val:.2f}", ha="center")')
L('        plt.tight_layout()')
L('        plt.savefig(self.output_dir / "resumen_general.png", dpi=150)')
L('        print(f"Guardado: {self.output_dir / \"resumen_general.png\"}")')
L('        fig2, ax = plt.subplots(figsize=(10, 6))')
L('        molestia_heatmap = self.df.groupby(["ruido", "nivel"])["molestia"].mean().unstack()')
L('        molestia_heatmap = molestia_heatmap.reindex(index=["road", "voices", "nature"], columns=["low", "equal", "high"])')
L('        im = ax.imshow(molestia_heatmap.values, cmap="RdYlGn_r", aspect="auto", vmin=0, vmax=10)')
L('        ax.set_xticks(range(3))')
L('        ax.set_xticklabels(["Low (-8dB)", "Equal", "High (+8dB)"])')
L('        ax.set_yticks(range(3))')
L('        ax.set_yticklabels(["Trafico", "Voces", "Naturaleza"])')
L('        ax.set_title("Mapa de calor: Molestia media por combinacion")')
L('        plt.colorbar(im, ax=ax, label="Molestia")')
L('        for i in range(3):')
L('            for j in range(3):')
L('                ax.text(j, i, f"{molestia_heatmap.values[i, j]:.1f}",')
L('                         ha="center", va="center", color="black", fontsize=12)')
L('        plt.tight_layout()')
L('        plt.savefig(self.output_dir / "heatmap_molestia.png", dpi=150)')
L('        print(f"Guardado: {self.output_dir / \"heatmap_molestia.png\"}")')
L('        fig3, axes3 = plt.subplots(2, 4, figsize=(16, 8))')
L('        afectivas = ["afectiva_agradable", "afectiva_caotico", "afectiva_estimulante",')
L('                     "afectiva_sinactividad", "afectiva_calmado", "afectiva_molesto",')
L('                     "afectiva_conactividad", "afectiva_monotono"]')
L('        nombres = ["Agradable", "Caotico", "Estimulante", "Sin act.", "Calmado", "Molesto", "Con act.", "Monotono"]')
L('        for idx, (af, nom) in enumerate(zip(afectivas, nombres)):')
L('            row = idx // 4')
L('            col = idx % 4')
L('            media_ruido = self.df.groupby("ruido")[af].mean()')
L('            axes3[row, col].bar(media_ruido.index, media_ruido.values, color=["#e74c3c", "#3498db", "#2ecc71"])')
L('            axes3[row, col].set_title(f"{nom}")')
L('            axes3[row, col].set_ylabel("Media (1-5)")')
L('            axes3[row, col].set_ylim(0, 5)')
L('        plt.tight_layout()')
L('        plt.savefig(self.output_dir / "afectivas_por_ruido.png", dpi=150)')
L('        print(f"Guardado: {self.output_dir / \"afectivas_por_ruido.png\"}")')
L('        plt.close("all")')
L('')
L('    def guardar_resultados(self):')
L('        output_file = self.output_dir / "informe.txt"')
L('        with open(output_file, "w", encoding="utf-8") as f:')
L('            import sys')
L('            from io import StringIO')
L('            old_stdout = sys.stdout')
L('            sys.stdout = StringIO()')
L('            self.info_general()')
L('            self.estadisticas_molestia()')
L('            self.estadisticas_fuentes()')
L('            self.estadisticas_afectivas()')
L('            output = sys.stdout.getvalue()')
L('            sys.stdout = old_stdout')
L('            f.write(output)')
L('            print(f"Informe guardado: {output_file}")')
L('')
L('    def run_all(self):')
L('        self.info_general()')
L('        self.estadisticas_molestia()')
L('        self.estadisticas_fuentes()')
L('        self.estadisticas_afectivas()')
L('        self.generar_graficos()')
L('        self.guardar_resultados()')
L('        print()')
L('        print("Analisis completado!")')
L('')
L('')
L('if __name__ == "__main__":')
L('    import sys')
L('    if len(sys.argv) < 2:')
L('        print("Uso: python analizar_resultados.py <ruta_al_csv>")')
L('        sys.exit(1)')
L('    csv_path = sys.argv[1]')
L('    analyzer = Analyzer(csv_path)')
L('    analyzer.run_all()')

with open(os.path.join(os.path.dirname(__file__), 'analizar_resultados.py'), 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print('Done writing analizar_resultados.py')
